### ISSUE TITLE
Audio control

### ISSUE THREAD

**Issue by KiteAB** [theniceboy/scripts#2]
I use mod+backslash to toggle my volume ( vol-toggle.sh ), but my dwm status bar can't feedback the volumn switch.

For example, my volume is 45%, and then I press mod+backslash, the status bar still shows 45%, but I can’t hear it when playing audio and video, I try to manually refresh the status bar, the problem remains

**Comment by KiteAB** [comment]
@theniceboy

**Comment by theniceboy** [comment]
make that sure you have the necessary software installed

**Comment by theniceboy** [comment]
Again, closing, as it's not an issue of this repo.

**Comment by KiteAB** [comment]
Is it not?
